language: node_js
node_js:
  - 12.3.1
cache: npm
before_script: npm install -g gulp-cli
script: gulp ci
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master