language: node_js
node_js: 12.3.1
cache: npm
script: npm run build
after_script: npm run clean:ci
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master