---
name: CI

on:
  push:
    branches:
      - master
      - 'bugfix/**'
      - 'feature/**'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/setup-node@v1.4.2
        with:
          node-version: '13'
      - run: yarn install
      - run: yarn run lint
      - run: yarn test
        if: startsWith(github.ref, 'refs/heads/bugfix/') || startsWith(github.ref, 'refs/heads/feature/')
      - uses: paambaati/codeclimate-action@v2.6.0
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: yarn test
          debug: true
      - name: Build
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: yarn run build:prod
      - name: Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: crazy-max/ghaction-github-pages@v1.5.1
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
