---
name: CI

on:
  push:
    branches:
      - main
      - 'bugfix/**'
      - 'bump/patch-**'
      - 'feature/**'

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.ref }}
      - name: Cache node_modules
        id: yarn-cache
        uses: actions/cache@v2.1.3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Compile
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        run: yarn install
      - name: Lint
        run: yarn run lint
      - name: Security tests
        run: |
          yarn run security:auth ${{ secrets.SNYK_API_TOKEN }}
          yarn run security:test
      - name: Unit tests
        run: yarn run test
        if: github.event_name == 'push' && github.ref != 'refs/heads/main'
      - name: Unit tests with coverage
        uses: paambaati/codeclimate-action@v2.7.5
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: yarn test
          debug: true
      - name: Build
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: yarn run build:prod
      - name: Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
