---
name: Deploy

on:
  push:
    branches:
      - 'test-*'

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Prepare bundle
        run: ./build_bundle.sh
      - name: Move bundle
        run: mv business-card-payload.zip ./terraform/business-card-payload.zip
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Format
        id: fmt
        run: cd terraform && terraform fmt -check
      - name: Terraform Init
        id: init
        run: cd terraform && terraform init
      - name: Terraform Validate
        run: cd terraform && terraform validate -no-color
      - name: Terraform Plan
        id: plan
        run: cd terraform && terraform plan -no-color
        continue-on-error: true
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
#      - name: Terraform Apply
#        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
#        run: cd terraform && terraform apply -auto-approve -var 'payload_path=./server/business-card-payload.zip'
