---
name: Deploy

on:
  push:
    branches:
      - 'test-*'

jobs:
  prepare_bundle:
    name: Prepare bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Prepare bundle
        run: cd server && ./build_bundle.sh
      - uses: actions/upload-artifact@v2
        with:
          name: business-card-payload
          path: server/business-card-payload.zip
          retention-days: 5
  terraform:
    name: Terraform
    needs: prepare_bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Download payload
        uses: actions/download-artifact@v2
        with:
          name: business-card-payload
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Format
        id: fmt
        run: cd terraform && terraform fmt -check
      - name: Terraform Init
        id: init
        run: cd terraform && terraform init
      - name: Terraform Validate
        run: cd terraform && terraform validate -no-color
      - name: Terraform Plan
        id: plan
        run: cd terraform && terraform plan -no-color -var 'payload_path=../business-card-payload.zip'
        continue-on-error: true
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
#      - name: Terraform Apply
#        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
#        run: cd terraform && terraform apply -auto-approve -var 'payload_path=./server/business-card-payload.zip'
