---
name: SAST

on: # yamllint disable-line rule:truthy
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  security:
    name: Security
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: fabasoad/reusable-workflows/.github/workflows/wf-security-sast.yml@main
    with:
      code-scanning: true
      sca: true
      sca-vendor: osv-scanner
