---
name: Sync labels

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - fix/ci
#    paths:
#      - .github/labels.yml
#      - .github/workflows/sync-labels.yml
  workflow_dispatch:

jobs:
  sync-labels:
    name: Sync labels
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Run Label Syncer
        uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
