---
name: Test

on:
  push:
    branches:
      - 'fix-pipeline'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Print versions
        run: node --version
      - name: Compile
        run: yarn install --ignore-scripts
      - name: Build
        run: yarn run build:prod
