---
name: Trigger deployment

on:
  push:
    branches:
      - 'test-*'
    tags:
      - 'v*'

jobs:
  trigger_deployment:
    name: Send request
    runs-on: ubuntu-latest
    steps:
      - name: Send request to fabasoad/business-card-deployment
        run: |
          echo "Sending ${{ github.ref }}"
          curl -XPOST -u "fabasoad:${{secrets.GITHUB_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/fabasoad/business-card-deployment/actions/workflows/terraform.yml/dispatches --data '{"tag": "${{ github.ref }}"}'
