---
name: Unit Tests

on:
  pull_request:
    paths:
      - .github/workflows/unit-tests.yml
      - .tool-versions
      - jest.config.json
      - package.json
      - src/**
      - tsconfig.json
  push:
    branches:
      - main

jobs:
  jest:
    name: Jest
    uses: fabasoad/reusable-workflows/.github/workflows/wf-js-unit-tests.yml@feat/js-ut
    secrets:
      code-climate-test-reporter-id: "${{ secrets.CC_TEST_REPORTER_ID }}"
