---
name: Unit Tests

on:
  push:
    branches:
      - 'main'
      - 'fix-*'
      - 'feature-*'

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache node_modules
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-
      - name: Compile
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        run: yarn install --ignore-scripts
      - name: Lint
        run: yarn run lint
      - name: Unit tests
        if: github.event_name == 'push' && github.ref != 'refs/heads/main'
        run: yarn test
      - name: Unit tests with coverage
        uses: paambaati/codeclimate-action@v3.0.0
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: yarn test
          debug: true
